post:
  summary: Submit application process form
  parameters:
    - $ref: ../components/parameters/contactIdParam.yaml
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/FormSubmitRequest.yaml
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              version:
                type: integer
              count:
                type: integer
                const: 1
              values:
                type: array
                maxItems: 1
                minItems: 1
                items:
                   $ref: ../components/schemas/FormSubmitResponse.yaml
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ErrorResponse.yaml
