name: PHPStan

on:
  push: ~
  pull_request:
    branches: [ main ]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        prefer: ['prefer-stable', 'prefer-lowest']
    name: PHPStan with PHP ${{ matrix.php-versions }} ${{ matrix.prefer }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
      env:
        fail-fast: true

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}-${{ matrix.prefer }}-
        restore-keys: ${{ runner.os }}-composer-${{ matrix.prefer }}-

    - name: Install dependencies
      run: composer update --prefer-dist --${{ matrix.prefer }}

    - name: Run PHPStan
      run: composer phpstan -- analyse -c phpstan.ci.neon
